export const ROLE_NAMES = ['admin', 'general_manager', 'department_manager', 'employee'] as const;
export type RoleName = typeof ROLE_NAMES[number];

export const ROLE_LABELS: Record<RoleName, string> = {
  admin: 'Administrador',
  general_manager: 'Gerente General',
  department_manager: 'Responsable de Departamento',
  employee: 'Empleado',
};

export const PERMISSIONS = [
  'users:view',
  'users:create',
  'users:update',
  'users:delete',
  'schedules:view',
  'schedules:create',
  'schedules:update',
  'schedules:delete',
  'schedule_types:read',
  'schedule_types:create',
  'schedule_types:update',
  'schedule_types:delete',
  'branches:view',
  'branches:create',
  'branches:update',
  'branches:delete',
  'branches:holidays:manage',
  'departments:view',
  'departments:create',
  'departments:update',
  'departments:delete',
  'settings:view',
  'settings:update',
  'audit:view',
  'vacations:create',
  'vacations:read',
  'vacations:read-all',
  'vacations:approve',
  'vacations:cancel',
  'vacations:delete',
  'shift_presets:read',
  'shift_presets:create',
  'shift_presets:update',
  'shift_presets:delete',
] as const;
export type PermissionName = typeof PERMISSIONS[number];

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  admin: [
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'schedules:view',
    'schedules:create',
    'schedules:update',
    'schedules:delete',
    'schedule_types:read',
    'schedule_types:create',
    'schedule_types:update',
    'schedule_types:delete',
    'branches:view',
    'branches:create',
    'branches:update',
    'branches:delete',
    'branches:holidays:manage',
    'departments:view',
    'departments:create',
    'departments:update',
    'departments:delete',
    'settings:view',
    'settings:update',
    'audit:view',
    'vacations:create',
    'vacations:read',
    'vacations:read-all',
    'vacations:approve',
    'vacations:cancel',
    'vacations:delete',
    'shift_presets:read',
    'shift_presets:create',
    'shift_presets:update',
    'shift_presets:delete',
  ],
  general_manager: [
    // Nota: Aunque tiene permisos de gestión, la lógica de negocio en el servicio
    // restringe sus acciones CRUD (Crear, Actualizar, Borrar) a su propia sucursal.
    // Schedule Types: solo lectura — solo admin puede crear/editar/borrar.
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'schedules:view',
    'schedules:create',
    'schedules:update',
    'schedules:delete',
    'schedule_types:read',
    'branches:view',
    'branches:holidays:manage',
    'departments:view',
    'settings:view',
    'vacations:create',
    'vacations:read',
    'vacations:read-all',
    'vacations:approve',
    'vacations:cancel',
    'shift_presets:read',
  ],
  department_manager: [
    'users:view',
    'users:update',
    'schedules:view',
    'schedules:create',
    'schedules:update',
    'schedules:delete',
    'schedule_types:read',
    'branches:view',
    'departments:view',
    'settings:view',
    'vacations:create',
    'vacations:read',
    'vacations:read-all',
    'vacations:approve',
    'vacations:cancel',
    'shift_presets:read',
  ],
  employee: [
    'schedules:view',
    'schedule_types:read',
    'branches:view',
    'vacations:create',
    'vacations:read',
    'vacations:cancel',
  ],
};
